#!/usr/bin/python3
"""Fresh installed passive-monitor acceptance on real wlan0. No injected captures."""
import argparse
import csv
import dataclasses
import json
import subprocess
import threading
import time
from pathlib import Path
from unittest.mock import patch
import netlab
from PySide6.QtWidgets import QApplication
from netlab.config import CONFIG
from netlab.gui.main_window import MainWindow
from netlab.gui import theme
from netlab.capture.pcapio import iter_capture_file
from netlab.analyze.decode import decode

parser=argparse.ArgumentParser()
parser.add_argument('--output',type=Path,required=True)
args=parser.parse_args();args.output.mkdir(parents=True,exist_ok=True)
assert netlab.__version__=='1.3.0'
assert netlab.__file__.startswith('/usr/lib/python3/dist-packages/'),netlab.__file__
CONFIG.set('capture_dir',str(args.output));CONFIG.set('bpf_filter','')
app=QApplication([]);app.setStyleSheet(theme.STYLESHEET)
w=MainWindow();w.show()
errors=[];w.capture.failed.connect(errors.append)
result=dict(version=netlab.__version__,module=netlab.__file__,platform=app.platformName(),started=time.time())


def pump(seconds):
    end=time.monotonic()+seconds
    while time.monotonic()<end:
        app.processEvents();time.sleep(.01)


def wait(predicate,timeout=30):
    end=time.monotonic()+timeout
    while time.monotonic()<end:
        pump(.05)
        if errors:raise RuntimeError(errors)
        if predicate():return
    raise TimeoutError('acceptance condition timed out')


def shot(name):
    pump(.15)
    assert w.grab().save(str(args.output/(name+'.png')))


traffic_results=[]
def traffic():
    commands=[['dig','-b',own,'httpforever.com','A','+tries=1','+time=5'],
              ['curl','--interface','wlan0','--noproxy','*','--max-time','20','-sS','-o','/dev/null','-w','%{http_code}','http://httpforever.com/'],
              ['curl','--interface','wlan0','--noproxy','*','--max-time','20','-sS','-o','/dev/null','-w','%{http_code}','https://www.google.com/']]
    for command in commands:
        p=subprocess.run(command,capture_output=True,text=True,timeout=25)
        traffic_results.append(dict(command=command,returncode=p.returncode,stdout=p.stdout,stderr=p.stderr))


def more_http():
    command=['curl','--interface','wlan0','--noproxy','*','--max-time','20','-sS','-o','/dev/null','-w','%{http_code}','http://httpforever.com/']
    p=subprocess.run(command,capture_output=True,text=True,timeout=25)
    traffic_results.append(dict(command=command,returncode=p.returncode,stdout=p.stdout,stderr=p.stderr))


try:
    pump(.4)
    idx=w.iface_combo.findData('wlan0');assert idx>=0
    w.iface_combo.setCurrentIndex(idx)
    w.bpf_edit.setText('arp or port 53 or tcp port 80 or tcp port 443 or icmp')
    w.start_btn.click()
    wait(lambda:w.capture.is_running and bool(w.analysis.hosts.context.addresses))
    own=next(a[0] for a in w.analysis.hosts.context.addresses if ':' not in a[0])
    result['selected_ip']=own
    result['selected_role']='This Device; traffic generated by this test host, not an unobserved peer'
    w._goto('Devices')
    wait(lambda:w.devices_page.model.rowCount()>0)
    assert w.devices_page.select_device(own)
    w.devices_page.monitor_button.click()
    m=w.monitor_page
    wait(lambda:m.snapshot is not None)
    assert w.stack.currentWidget() is m
    assert own in w.monitor_indicator.text()
    initial=m.snapshot.device.packets
    worker=threading.Thread(target=traffic,daemon=True);worker.start()
    wait(lambda:not worker.is_alive(),75)
    assert all(p['returncode']==0 for p in traffic_results),traffic_results
    wait(lambda:m.snapshot.device.packets>initial and all(m.snapshot.counts[k]>0 for k in ('dns','http','tls')))
    wait(lambda:any(t.sni=='www.google.com' for t in m.snapshot.tls) and any(t.host=='httpforever.com' for t in m.snapshot.http))
    s=m.snapshot
    assert all(own in (r.src,r.dst) for r in s.activity)
    assert all(r.direction==('LOCAL' if r.src==r.dst==own else 'OUT' if r.src==own else 'IN') for r in s.activity)
    assert all(own in (f.client,f.server) for f in s.connections)
    assert all(own in (d.src,d.dst) or own in d.resolved_ips for d in s.dns)
    assert all(own in (t.client,t.server) for t in (*s.http,*s.tls))
    observed=[d for d in w.analysis.device_view()[0] if d.packets>0]
    assert len(observed)>1
    result['observed_endpoints']=[dict(ip=d.ip,packets=d.packets,scope=d.scope) for d in observed]
    result['monitor_snapshot']=dict(packets=s.device.packets,bytes=s.device.bytes,initial_packets=initial,
        dns=s.counts['dns'],http=s.counts['http'],tls=s.counts['tls'],connections=s.counts['active_connections'],
        activity_rows=len(s.activity),directions=sorted({r.direction for r in s.activity}))
    result['protocol_evidence']=dict(
        dns=[dict(query=e.qname,type=e.qtype,answer=e.answer_summary) for e in s.dns if e.qname in ('httpforever.com','www.google.com')],
        http=[dict(host=t.host,method=t.method,status=t.status) for t in s.http if t.host=='httpforever.com'],
        tls=[dict(sni=t.sni,version=t.negotiated_version or t.server_version,alpn_selected=t.alpn_selected,
                  alpn_offered=t.alpn_offered,cipher=t.cipher_suite,flow_bytes=s.tls_bytes.get(t.flow_key,[None])[0])
             for t in s.tls if t.sni=='www.google.com'])
    shot('monitor-activity')
    for name in ('Connections','DNS','HTTP','TLS'):
        m.tabs.setCurrentWidget(m.tables[name]);shot('monitor-'+name.lower())
        assert m.models[name].rowCount()>0,name
    # Clicking a retained connection reaches its existing session view.
    m.tables['Connections'].clicked.emit(m.models['Connections'].index(0,0))
    assert w.stack.currentWidget() is w.connections_page
    w._goto('Selected Device')
    m.buttons['Pause'].click()
    frozen=m.snapshot; frozen_revision=m.revisions
    before=w.analysis.stats().total_packets
    worker=threading.Thread(target=more_http,daemon=True);worker.start()
    wait(lambda:not worker.is_alive(),30)
    wait(lambda:w.analysis.stats().total_packets>before)
    assert m.snapshot is frozen and m.revisions==frozen_revision
    shot('monitor-paused')
    m.buttons['Resume'].click()
    wait(lambda:m.revisions>frozen_revision and m.snapshot.device.packets>frozen.device.packets)
    result['pause_resume']=dict(frozen_packets=frozen.device.packets,resumed_packets=m.snapshot.device.packets,global_capture_continued=True)
    target=args.output/'selected-device.pcapng'
    with patch('netlab.gui.pages.monitor.QFileDialog.getSaveFileName',return_value=(str(target),'')):
        m.buttons['Export Device Traffic'].click()
    wait(lambda:target.exists() and not m._export_busy)
    packets=list(iter_capture_file(target))
    assert packets
    for raw in packets:
        p=decode(raw.data,raw.linktype,raw.ts,raw.wirelen)
        assert own in (p.src,p.dst)
    independent=subprocess.check_output(['tshark','-r',str(target),'-T','fields','-e','frame.number'],text=True)
    capinfos=subprocess.check_output(['capinfos','-Tm','-c',str(target)],text=True)
    assert len(packets)==len(independent.splitlines())==int(list(csv.reader(capinfos.splitlines()))[-1][-1])
    only_selected=subprocess.check_output(['tshark','-r',str(target),'-Y',f'ip.addr == {own} || arp.src.proto_ipv4 == {own} || arp.dst.proto_ipv4 == {own}', '-T','fields','-e','frame.number'],text=True)
    assert len(only_selected.splitlines())==len(packets)
    result['export']=dict(path=str(target),netlab=len(packets),tshark=len(independent.splitlines()),capinfos=len(packets),all_packets_match_selected_ip=True)
    before=w.analysis.stats().total_packets
    m.buttons['Stop Monitoring'].click()
    stopped_revision=m.revisions
    assert not m.registry.subscriptions and w.monitor_indicator.text()==''
    assert w.capture.is_running
    worker=threading.Thread(target=more_http,daemon=True);worker.start()
    wait(lambda:not worker.is_alive(),30)
    wait(lambda:w.analysis.stats().total_packets>before)
    assert w.capture.is_running and m.revisions==stopped_revision
    assert m.models['Activity'].rowCount()==0
    result['stop_monitoring']=dict(global_packets_before=before,global_packets_after=w.analysis.stats().total_packets,
        global_capture_still_running=True,monitor_subscription_removed=True)
    shot('monitor-stopped-capture-running')
    w.stop_btn.click();wait(lambda:not w.capture.is_running);pump(.5)
    source=w._source_path
    original=[]
    for raw in iter_capture_file(source):
        p=decode(raw.data,raw.linktype,raw.ts,raw.wirelen)
        if own in (p.src,p.dst):original.append(raw.data)
    assert [p.data for p in packets]==original[:len(packets)]
    result['export']['original_bytes_preserved']=True
    result['source_pcap']=str(source)
    result['final_stats']=dataclasses.asdict(w.analysis.stats())
    result['traffic_commands']=traffic_results
    assert all(p['returncode']==0 for p in traffic_results)
    result['passed']=True
finally:
    result['completed']=time.time()
    (args.output/'acceptance.json').write_text(json.dumps(result,indent=2)+'\n')
    if w.capture.is_running:w.stop_capture()
    w.close()
print(json.dumps(result,indent=2))
